id: A0B886684
title: The Concise Mahāmudrā Preliminaries Arranged for Recitation
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:33:18.377876
  last_modified_at: 2022-03-01 04:33:18.377882
