id: A0B886684
title: Aspiration of the Mahāmudrā of Definitive Meaning
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:33:18.374155
  last_modified_at: 2022-03-01 04:33:18.374163
